CREATE TABLE "model_data" (
	"id"	INTEGER,
	"batch_no"	TEXT,
	"data_hash_code"	TEXT,
	"model_name"	TEXT NOT NULL,
	"jgbm"	TEXT,
	"jgmc"	TEXT,
	"sjrq"	TEXT,
	"field1"	TEXT,
	"field2"	TEXT,
	"field3"	TEXT,
	"field4"	TEXT,
	"field5"	TEXT,
	"field6"	TEXT,
	"field7"	TEXT,
	"field8"	TEXT,
	"field9"	TEXT,
	"field10"	TEXT,
	"field11"	TEXT,
	"field12"	TEXT,
	"field13"	TEXT,
	"field14"	TEXT,
	"field15"	TEXT,
	"field16"	TEXT,
	"field17"	TEXT,
	"field18"	TEXT,
	"field19"	TEXT,
	"field20"	TEXT,
	"create_time"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
)